[webservers]
web1 ansible_host=40.81.12.237 app_server_name=vm-redesProject1
web2 ansible_host=20.245.41.157 app_server_name=vm-redesProject2

[webservers:vars]
ansible_user=RedesProject
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3